name: On commit

on: push

jobs:
  my-job:
    name: Publish to Surge.sh
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to flaky-toothbrush.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://flaky-toothbrush.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}